### ISSUE TITLE
make number of lookups which are cached configurable

### ISSUE THREAD

**Issue by evdama** [ipregistry/ipregistry-javascript#1]
I reckon it would make sense to maybe keep a default of 16 resp. 2048 lookups which are cached but make it configurable so that one could set the cache on his server to e.g. 16384 lookups which are cached.

**Comment by lpellegr** [comment]
@evdama Thanks for your feedback.

This is already possible to configure the maximum number of entries that are stored in the cache:

```javascript
const client = new IpregistryClient('tryout', new DefaultCache(16384));
```

Here is a link to the cache code if you want to check what parameters are available:

https://github.com/ipregistry/ipregistry-javascript/blob/2196ba41dcfe0e2bcfc81d5f61fa047b38febfca/src/cache.ts#L42

I will add an example in the README and some samples in the corresponding folder.

**Comment by evdama** [comment]
ah, right, sorry for the noise... I was about to check the source as well tonight.
Also, if you add some example to the README, please also add a an example how to make a call with a filter, like for example, I want to rewrite my custom axios call to this lib using those filters
`hostname,location%5Bin_eu,country.name%5D,security%5Bis_threat,is_anonymous,is_tor_exit,is_bogon%5D` with basically this server route

```
// export default async ( ipAddress, filters ) => {
//   try {
//     const ipRegistryResponse = await axios.get( `ROLLUP_IPREGISTRY_URL${ ipAddress }?key=ROLLUP_IPREGISTRY_KEY&hostname=true&fields=${ filters }` )
//     return ipRegistryResponse.data
//   } catch ( error ) {
//     console.log('error from call-to-ipregistry-api.js')
//   }
// }
```

**Comment by lpellegr** [comment]
Done:

https://github.com/ipregistry/ipregistry-javascript/blob/master/README.md#caching

Thanks for your trust!

Do not hesitate to create a new issue or contact us by email if you have any questions.
