### ISSUE TITLE
Send API Key in headers

### ISSUE THREAD

**Issue by matiaslopezd** [ipregistry/ipregistry-javascript#103]
How I can send the API key in headers with this library?

Also, I believe is too necessary to suggest using the "Authorization" header to maintain safe the API Key, instead of the param in the URL.

Thanks!

**Comment by lpellegr** [comment]
The solution to use really depends on your use case. As you said, using a header is a good practice in general. You can find an example of how to use the _Authorization_ header on the next page:

https://ipregistry.co/docs/authentication#content

**Comment by matiaslopezd** [comment]
@lpellegr thanks, but I try to do with this library. Now I see that is possible to send options to `IpregistryClient` like `apiKey`, `timeout`, and `apiUrl` in the first param.

```js
const options = { apiKey, timeout, apiUrl };
const cache = new DefaultCache(1000, 3600000);
const iDontKnowWhatParamsReceiveThisFunction = IpregistryRequestHandler(??);
const client = new IpregistryClient(options, cache, ???);
```

There is documentation related to these params? I want to send the API key on headers :)

Thanks!

**Comment by lpellegr** [comment]
Oops, I read your original message too quickly. Sorry about that. 

An option is to pass a custom _RequestHandler_ implementation that overrides the default one. However, that's really not convenient. Furthermore, I agree with you that we would pass the API key as a header by default. 

I will make the changes by Friday, release a new version, and let you know.

**Comment by matiaslopezd** [comment]
Thanks @lpellegr! 👏👏👏

**Comment by lpellegr** [comment]
@matiaslopezd It was faster than expected. I have published version _3.1.0_:

https://www.npmjs.com/package/@ipregistry/client

Please let me know whether it works as desired.

**Comment by matiaslopezd** [comment]
@lpellegr works perfectly! That commit was too fast! Thanks!!!! 🎉🎉🎉
