### ISSUE TITLE
TypeScript Typing for Language Section Contains Mismatch

### ISSUE THREAD

**Issue by copyrighthero** [ipregistry/ipregistry-javascript#183]
Hello there!

Thank you very much for this great project and your solid product!

However it seems the `Language` model's `native_name: string | null;` should've been `native: string | null;` instead, I'm wondering if you could double check?

Thank you and hope you have a great day!

Regards,
Hansheng

**Comment by lpellegr** [comment]
@copyrighthero Thanks for creating this issue and sorry for the late answer. It looks like I did not see the notification about this issue. A fix has been committed and a new release will be published soon.

**Comment by lpellegr** [comment]
Version 4.1.0 has been released.
