### ISSUE TITLE
import issues with Svelte / Sapper Project

### ISSUE THREAD

**Issue by evdama** [ipregistry/ipregistry-javascript#2]
I'm using [Sapper](https://sapper.svelte.dev/docs/) which does  server side rendering. There I have code calling the IPRegistry API using the javascript library of yours:
```js
import { IpregistryClient, DefaultCache, IpregistryOptions } from '@ipregistry/client'

export default async ( ipAddress, filters ) => {
  try {
    const IPRClient = new IpregistryClient( `ROLLUP_IPREGISTRY_KEY`, new DefaultCache(16384) )

        return await IPRClient.lookup( ipAddress, IpregistryOptions.hostname(true), IpregistryOptions.filter(filters) )

  } catch ( error ) {
    console.log('error from call-to-ipregistry-api.js')
  }
}
```

Because with sapper you do SSR, then ship the page down to the client, den hydrate it you've to basically take care of server and client when importing. Other ES6 imports work fine, but using `/@ipregistry/client` I get this error in the console

```sh
src/node_modules/utils/ipregistry/call-to-ipregistry-api.js changed. rebuilding...
✗ client
'IpregistryClient' is not exported by node_modules/@ipregistry/client/dist/browser/index.js
1: import { IpregistryClient, DefaultCache, IpregistryOptions } from '@ipregistry/client'
            ^
2:
3: export default async ( ipAddress, filters ) => {
✗ server
'DefaultCache' is not exported by node_modules/@ipregistry/client/dist/esm/index.js
1: import { IpregistryClient, DefaultCache, IpregistryOptions } from '@ipregistry/client'
                              ^
2:
3: export default async ( ipAddress, filters ) => {
✔ service worker (29ms)
```

Note that a native axios version works just fine. This is what I had before:
```js
import axios from 'axios'

export default async ( ipAddress, filters ) => {
  try {
    const ipRegistryResponse = await axios.get( `ROLLUP_IPREGISTRY_URL${ ipAddress }?key=ROLLUP_IPREGISTRY_KEY&hostname=true&fields=${ filters }` )
    return ipRegistryResponse.data
  } catch ( error ) {
    console.log('error from call-to-ipregistry-api.js')
  }
}
```

**Comment by lpellegr** [comment]
Thanks for raising this issue. I don't have the time to investigate right now but I will do it at the beginning of the next week.

**Comment by lpellegr** [comment]
I was able to reproduce and fix the issue.

The default Ipregistry bundle loaded by sapper on browsers does export Ipregistry classes, nor a default export. Only the ESM bundle does.

I have published a [new version](https://www.npmjs.com/package/@ipregistry/client) of the Ipregistry client library (1.2.1) and written a small working example with sapper:

https://github.com/ipregistry/ipregistry-sapper

The file that you are interested in is `src/routes/ipregistry.svelte`:

https://github.com/ipregistry/ipregistry-sapper/blob/109535c12111ac8f65843c661a99fb286e041f4f/src/routes/ipregistry.svelte#L3-L17

**Comment by evdama** [comment]
brilliant, I'll test this tonight and report back here!

**Comment by lpellegr** [comment]
Your support and trust are really appreciated. Thanks!

**Comment by evdama** [comment]
so I've settled with this code which works just fine
```js
import ipregistry from '@ipregistry/client'

export default async ( ipAddress, filters ) => {
  try {
    const client = new ipregistry.IpregistryClient('ROLLUP_IPREGISTRY_KEY', new ipregistry.DefaultCache(16384))
    return await client.lookup(ipAddress,
      ipregistry.IpregistryOptions.hostname(true),
      ipregistry.IpregistryOptions.filter(filters))
  } catch ( error ) {
    console.log( 'IPRegistry error code: ' + error.code )
    console.log( 'IPRegistry error message: ' + error.message )
    console.log( 'IPRegistry error resolution: ' + error.resolution )
  }
}
```

two more things

 - if you see any room for improvement above, let me know :)
 - I'd like to not make IPR requests for bots and crawlers. not sure how I'd add https://github.com/ipregistry/ipregistry-javascript/blob/353061026c0a739164cb06b5fb060116a9e4a549/src/util.ts#L17-L24 to the above? I would have to exract the `user-agent` header from the HTTP request yes? then use it with this function yes? can you maybe point me in the right direction?

**Comment by lpellegr** [comment]
Thanks for your feedback. 

I don't know where you call the functions above but be careful. As you know, with Sapper, the same code may be called on server-side and client-side depending on where you put the code. This means that you will most probably have to check if the `window` variable is defined to detect the environment and adapt how the user-agent is retrieved:

```javascript
req.headers['user-agent']
```

on server-side with expressjs, or 

```javascript
navigator.userAgent
```

on client-side.

Please create a separate issue if you encounter any problems.
