### ISSUE TITLE
`is_tor_exit` not available as type

### ISSUE THREAD

**Issue by evdama** [ipregistry/ipregistry-javascript#242]
The API response is `is_tor_exit` whereas the type definition is `is_tor_exit_node` https://github.com/ipregistry/ipregistry-javascript/blob/fc20cc121d1e6f298fa1cba7f5d425d4540334ba/src/model.ts#L275 so visual studio code is complaining
![Screenshot 2022-04-03 at 21 37 13](https://user-images.githubusercontent.com/39374084/161445086-b22dcca7-2db0-4f5c-afc4-1fda7539875c.png)

**Comment by lpellegr** [comment]
@evdama Thanks for your report. A new version (4.4.2) that fixes the issue you reported has been published.

**Comment by evdama** [comment]
thanks 👍
