### ISSUE TITLE
Return Remaining Credit and Rate Limit from http response headers

### ISSUE THREAD

**Issue by baxford** [ipregistry/ipregistry-javascript#3]
Hi, I'm really happy with the library, however from my testing I see that the API returns the following headers:
      'Ipregistry-Credits',
      'X-Rate-Limit-Limit',
      'X-Rate-Limit-Remaining',

It would be great if the response from `client.lookup(ipAddress)`
could return these values so our application can notify us when we are approaching our limits.

I've put together a simple PR for my use-case here:
https://github.com/ipregistry/ipregistry-javascript/pull/4

thanks :)

**Comment by lpellegr** [comment]
@baxford Thanks for sharing your use case and creating a PR.

Adding support for accessing the headers you mention is definitively a great suggestion!

I will review your PR.

**Comment by lpellegr** [comment]
@baxford We've released a new version of the client (2.0.0) that includes a manner to retrieve usage data. The API is quite different from what you proposed in your PR but the idea remains the same:

https://github.com/ipregistry/ipregistry-javascript#usage-data

Please let me know whether it works as you need.
